## Array

In [3]:
import array as arr # this is how you would import an array, it shows error beause you have to define your array
arr.array()

TypeError: array() takes at least 1 argument (0 given)

In [5]:
from array import * # you can replace the star with the functions you want to work with but to keep it simple use * to import all functions

vals = array ('i', [2,52,23,199]) # we are using i here as we're gonna be working with both +ve & -ve int
print (vals)

array('i', [2, 52, 23, 199])


In [8]:
from array import *

val = array ('i', [1,40,23,10]) # this is a tuple
val.reverse() # reverses the sequence in which it appears
print (val)

array('i', [10, 23, 40, 1])


In [11]:
from array import * 
print (val[0]) # this prints the first value in the sequence, this is called indexing

10


#### what should we do if we want to print all the values? Use a for loop 

In [18]:
for i in range(4): # we use 4 here because there are only 4 values in the array
    print (val[i]) #remeb to take note that the i here has to be in square brackets []

10
23
40
1


In [20]:
for i in range (4): # lets do it one more time
    print (vals[i])

2
52
23
199


#### what if you don't know how many numbers are in the array? use len

In [35]:
print (len(vals))

4


In [42]:
for i in range (len(vals)): #it's taking the range in the length of vals
    print (vals[i])

2
52
23
199


In [41]:
for i in vals: # i can also do it like this instead of specifying the range
    print (i)

2
52
23
199


#### what if you don't know the type of the array but wanna create similar one? whether int, float etcetc.

In [9]:
from array import *
vals = array('i', [14,2,1,3])

newarr = array(vals.typecode, (a for a in vals))
for i in newarr:
    print(i)

14
2
1
3


#### circling back to indexing

In [27]:
vals = array ('i', [2,52,23,199])
print (vals[0])
print (vals[1])
print (vals[2])
print (vals[3])

2
52
23
199


In [43]:
vals = array ('i', [2,52,23,199])
print (vals[-1]) #gets the last number
print (vals[-2])
print (vals[-3])
print (vals[-4]) # gets the first number

199
23
52
2


### Array inputs from the user
* first, learn to create an empty array 

In [47]:
from array import * 

new = array("i", [])

In [48]:
n = int (input("Enter the length of the array"))  # the first step is to ask what's the length of the array they need

for i in range(n):
    x = int(input("Enter the next number"))
    new.append(x)
    
print (new)

Enter the length of the array 3
Enter the next number 2
Enter the next number 14
Enter the next number 21


array('i', [2, 14, 21])


In [12]:
from array import *
new = array('i', [])
a = int(input("input length of array: "))

for i in range(a):
    b = int(input("enter the next number"))
    new.append(b)
    
print(new)


input length of array:  3
enter the next number 1
enter the next number 4
enter the next number 2


array('i', [1, 4, 2])


### Searching for the index in the array

In [49]:
unknown = int(input("enter search value here to find out the index"))

k = 0
for e in new: # have to assign e instead of i like previously because it's looking for a value in the array, unlike previously when it's taking the range from 0
    if e == unknown: # checking if e (a value in the array) equals to the value the user input 
        print (k) # print k because you're looking through the loop 
        break
        
    k = k + 1

enter search value here to find out the index 14


1


## Numpys 

In [14]:
from numpy import *

In [30]:
x = array([15,2,3])
y = array([14,3,1])
print(x)
print(y)

[15  2  3]
[14  3  1]


In [23]:
x = array([15,2,3])
y = array([14,3,1])

print(concatenate([x,y]))

[15  2  3 14  3  1]


In [29]:
from numpy import * 
arr = array([
            [14,3,1], #do this as a 'shortcut' from point 1
            [12,4,1]
])

print(arr)

[[14  3  1]
 [12  4  1]]


In [33]:
from numpy import *
xyz = array([
            [4,4,1],
            [3,1,2],
            [10,12,1],
            [10,12,2]
])

print(xyz.ndim) #ndim is to find out how many dimensions there are

2


In [34]:
abc = array([
            [123,1,2,3],
            [123,4,2,3],
            [321,1,2,5]
])

print(abc.shape) # returns the number of columns & rows

(3, 4)


In [36]:
abc = array([
            [123,1,2,3],
            [123,4,2,3],
            [321,1,2,5]
])

print(abc.size) # returns the number of values

12


#### so this is currently 2D(2 dimensional, let's convert it to 1D using flatten)

In [38]:
abc = array([
            [123,1,2,3],
            [123,4,2,3],
            [321,1,2,5]
])

abc2 = abc.flatten()

print(abc2)

[123   1   2   3 123   4   2   3 321   1   2   5]


#### let's convert this 1D array into a 2D and 3D array
let's add more values, so that the total values is 12, it's easier to work with 3D arrays with 12 values 

2D array:
the syntax to add more is example: x1.reshape(2,4) 2 is the rows, 4 is the columns

In [43]:
x1 = array([
            [1,2,3,4,5,6],
            [1,2,3,4,5,6],
            
])

x2 = x1.flatten()

x3 = x2.reshape(4,3) # 4 rows and 3 columns. This is a 2D array

print(x3)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [45]:
x1 = array([
            [1,2,3,4,5,6],
            [1,2,3,4,5,6],
            
])

x2 = x1.flatten()

x3 = x2.reshape(2,2,3) #we have 2 total arrays in each dimension, 2 total dimensions, 3 vlaues in each array

print(x3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


#### Using matrix function to create a 2D array:
Instead of creating 2D array in the ways above, we can use the matrix function.
This allows more ways to work with the array 

let's use the old method first to recap:

In [50]:
arr = array ([
            [1,2,3],
            [4,5,6]
])

print(arr)

[[1 2 3]
 [4 5 6]]


now, let's use the matrix

In [49]:
m = matrix ('1,2,3 ; 4,5,6 ') #take note its not a colon, its a semi colon;
print(m)

[[1 2 3]
 [4 5 6]]


tadah! It's the same output!

with this you can also do pretty cool stuff like just getting the diagonal values. First lets convert to 3 rows and 3 columns so we can take the diagonal values

In [51]:
m = matrix ('1,2,3 ; 4,5,6 ; 1,6,7 ')
print(m)

[[1 2 3]
 [4 5 6]
 [1 6 7]]


In [53]:
print(diagonal(m)) 

[1 5 7]


In [55]:
print(m.min()) #takes the min value

1


Let's try this with an example

In [75]:
marks = array([
                [45,60,70],
                [50,80,95],
                [59,20,91],
    
        
])

print(marks)

[[45 60 70]
 [50 80 95]
 [59 20 91]]


In [76]:
print("Top scorer", marks.max())
print("Lowest mark", marks.min())
print("Class average", marks.mean())

Top scorer 95
Lowest mark 20
Class average 63.333333333333336


In [83]:
marks[1:3]

array([[50, 80, 95],
       [59, 20, 91]])

marks[start row index:end row index], [start column index]:[end column index]

In [95]:
print("First row", marks[0:1])
print("Second row", marks[1:2])
print("Third row", marks[2:3])

First row [[45 60 70]]
Second row [[50 80 95]]
Third row [[59 20 91]]


In [109]:
marks[0:1, 1:3] # I don't understand this concept

array([[60, 70]])

In [111]:
eng = [10,20,30]
math = [40,50,60]
sci = [70,80,90]
chi = [91,92,93]

score = array([eng, math, sci, chi])
print(score)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [91 92 93]]


In [115]:
score[1:3, 1:3] #second and third row, second and third column

array([[50, 60],
       [80, 90]])

In [116]:
score[1:2, 1:3] #second row only and second , second and third column

array([[50, 60]])

In [117]:
score[1:3, 1:2] # second and third row,  second row only

array([[50],
       [80]])

In [119]:
score[1:3, 1:2].sum()

130

In [122]:
score.sum()

726

In [123]:
score.sum(axis=0) #adds the columns (10+40+70+91)

array([211, 242, 273])

In [124]:
score.sum(axis=1) #adds the rows

array([ 60, 150, 240, 276])